// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt80b5hWmOo272IOyswUikzeyby263_aw',
    appId: '1:1013434571762:web:10d3ff3017c4a83897e96b',
    messagingSenderId: '1013434571762',
    projectId: 'buku-kontak-e555a',
    authDomain: 'buku-kontak-e555a.firebaseapp.com',
    storageBucket: 'buku-kontak-e555a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xOs9PcnZSQ0B1yP2DxNGGRB0V2yTWgA',
    appId: '1:1013434571762:android:10bf350fcabdce6a97e96b',
    messagingSenderId: '1013434571762',
    projectId: 'buku-kontak-e555a',
    storageBucket: 'buku-kontak-e555a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBovK4pV-VJz_EZ6qWr_lH-O0heC-5vPkQ',
    appId: '1:1013434571762:ios:d5e4e67981632eb997e96b',
    messagingSenderId: '1013434571762',
    projectId: 'buku-kontak-e555a',
    storageBucket: 'buku-kontak-e555a.firebasestorage.app',
    iosBundleId: 'com.example.kontakForm',
  );
}
